sudo: required
language: generic
jdk:
  - openjdk11
services:
  - docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "CITTXWQIOMxVXCA5SOsFWFJMQf/Ka7QVpmmOzUxexuU1HaxDSHtiff+wYrPDU8pgZG7Z+6d09tAkzLQzTlPuxn1KX+W13qcrH4/dp2M9n3z70rIRxAWTqDEfM+5NTeVSYfbEbUzuYY7pdkhfPddksltiGUCze3o5ockUwIWan/HI21OW98mEyvYq4vQOslbaZzuNvjPczDY0k5PvgTTUXUNLsCUKiG8ky+uCIs0OZ8EWFlzM2uHeMlgnIXomVjslay1mEBnaGxzugObTHDFWKWsc2UgbPHStkADABc8GBr6cPiqFpVGrDyc3/1mFSufSxCZa6Ac2mE0F/r99XHS8Ckq6/WlJMXCr3Grit3FvEZKbYV/9H+cuebc+Y726HpxZ5N8ZcfPSQfIirFFNUrURJThPjM4nzquS66teyr8P7E5qJysuXLAbs07bEXZgizz3aL4zbAUz7zhlR5KpnHVJ5f/IDbyoSnS+IFjrkCNZ0na1yaKOHm5qAB5a7yrGa48Oj4q2n2CIf6k+knzy+IIyJRtU83c+2i2ZeW1ajEJZ4Yh5irfsk5vqVo+gkOQCoqK7S7NqQ8WZ9+DM79YDHNoWEXZ0e/HTfYTer1ucB2j72kttoDKYIDCsmjWHjsysMKDGhRjbeGupDA75f6EfRNDAyZkqGBQV35l8JdzxyyMyWRs="
    # AWS_SECRET_ACCESS_KEY
    - secure: "nByfpn18Y29/2DngUFl+Pt/OBN5fEcfLNRQV5B9xurxos9tU9kSyExcXHeqfPRE8wZy+6Qa4MU6Ddf3B+aXeTWEHEbVA3cNwECoyBr1QLIiuVEs7/VPCWqavJtoJjmQSFbYBkncIi22Y9U4laBlY7831qWeYNhwmAE1T6m1DZXa08dxW+e0fTcOesj3Jc4NXlzEBzJ23NnZtssfsvHmkxEZZFq9czS4tU1MuxrWTa1pC6Lf5D71St2EbPbj7+msID3JaY+yTiCm6C5BJTSxXLQcz/VIVrsGa1clrZo1+xUMB5d+wh2zJ9U4lm9FbTaWvSKPQJW6eTYgEomB/WijgNsm3OFYIjRGkYqwUdMwXVkM6uLLKv1kYcPTdpXzkiF9wBPuM9SpoQpAuxkd3byJdjZYegIke97hkJpjsbQYD4Zacrbj5wTnLi8YMqjfGNUHP98Lrd+CVTsMGo2pFZ27jEGDwNk1I1D5njOAWH3jGB1ASirW++zS9Y012ibPQwYzbMg6oG2l5wC9Kqcdc6wmz+zVP6uLeQ8wjzC+QAXi7ge89k1kXepc+uI9cZNxq1frbku0BncD1LiHLZ/uypHkSw1VGHBPZZ8ZYPoMODG1WdiPdeZdNzBAgeVDmIHSXQtaI8yyqlitEuMNG0kf6ZyHsIjOsEsKW+MPNbBvDUJ82Td8="
cache:
  npm: true
  directories:
  - $HOME/.m2
  - node_modules
install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
before_script:
  - docker run --name liiteri-test-db -e POSTGRES_PASSWORD=oph -e POSTGRES_USER=oph -e POSTGRES_DB=liiteri -p 16433:5432 -d postgres:11
script: >-
  nvm install &&
  nvm use &&
  npm install &&
  CONFIG=dev-resources/local-test-config.edn ./bin/cibuild.sh run-tests-and-create-uberjar &&
  export BASE_IMAGE="baseimage-fatjar-openjdk11:master" &&
  ./ci-tools/common/pull-image.sh &&
  cp -v ./target/liiteri.jar $DOCKER_BUILD_DIR/artifact/liiteri.jar &&
  cp -vr ./oph-configuration $DOCKER_BUILD_DIR/config/ &&
  ./ci-tools/build/build-fatjar.sh liiteri
deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh liiteri
  on:
    all_branches: true
