version: '3.2'
services:
  liiteri-dev-db:
    image: postgres:11
    environment:
      - POSTGRES_DB=liiteri
      - POSTGRES_PASSWORD=oph
      - POSTGRES_USER=oph
    ports:
      - "16432:5432"
  liiteri-test-db:
    image: postgres:11
    environment:
      - POSTGRES_DB=liiteri
      - POSTGRES_PASSWORD=oph
      - POSTGRES_USER=oph
    ports:
      - "16433:5432"
  localstack:
    image: localstack/localstack:3.0.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
