CREATE TABLE files (
  id BIGSERIAL PRIMARY KEY,
  key VARCHAR(36) UNIQUE NOT NULL,
  filename VARCHAR(256) NOT NULL,
  content_type VARCHAR(128) NOT NULL,
  size BIGINT NOT NULL,
  uploaded TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  deleted TIMESTAMP WITH TIME ZONE
);
