CREATE TABLE file_versions (
  id       BIGSERIAL PRIMARY KEY,
  file_id  BIGINT NOT NULL REFERENCES files (id),
  version  VARCHAR(1024) UNIQUE NOT NULL,
  uploaded TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  deleted  TIMESTAMP WITH TIME ZONE
);

ALTER TABLE files DROP COLUMN uploaded;
ALTER TABLE files DROP COLUMN deleted;
