name: Liiteri

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        name: Install pnpm

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*
          cache: pnpm

      - name: Prepare clojure env
        uses: ./.github/actions/prepare-clojure-env

      - name: Run tests
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          GA_BUILD_NUMBER: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          docker run --name liiteri-test-db -e POSTGRES_PASSWORD=oph -e POSTGRES_USER=oph -e POSTGRES_DB=liiteri -p 16433:5432 -d postgres:15
          docker run --name liiteri-localstack -p 4566:4566 -d localstack/localstack:3.0.1
          pnpm install
          CONFIG=dev-resources/local-test-config.edn ./bin/cibuild.sh run-tests

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Prepare clojure env
        uses: ./.github/actions/prepare-clojure-env

      - name: Build
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: CONFIG=dev-resources/local-test-config.edn ./bin/cibuild.sh create-uberjar

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

  deploy:
    needs: [ test, build ]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: liiteri
      base-image: baseimage-fatjar-openjdk21:master
      configfolder: oph-configuration
      jarfile: liiteri
      jarfolder: target
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}

  deploy-background:
    needs: [ test, build ]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: liiteri-background
      base-image: baseimage-fatjar-openjdk21:master
      configfolder: oph-configuration
      jarfile: liiteri
      jarfolder: target
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
