name: Liiteri

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        name: Install pnpm

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Prepare clojure env
        uses: ./.github/actions/prepare-clojure-env

      - name: Run tests
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          GA_BUILD_NUMBER: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          docker run --name liiteri-test-db -e POSTGRES_PASSWORD=oph -e POSTGRES_USER=oph -e POSTGRES_DB=liiteri -p 16433:5432 -d postgres:15
          docker run --name liiteri-localstack -p 4566:4566 -d localstack/localstack:3.0.1
          pnpm install
          CONFIG=dev-resources/local-test-config.edn ./bin/cibuild.sh run-tests

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Prepare clojure env
        uses: ./.github/actions/prepare-clojure-env

      - name: Build
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: CONFIG=dev-resources/local-test-config.edn ./bin/cibuild.sh create-uberjar

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

  deploy:
    needs: [ test, build ]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@2f06269d5ac067ef17a76d2d5742db0b325e9a2e # main
    with:
      application: liiteri
      base-image: baseimage-fatjar-openjdk21:master
      configfolder: oph-configuration
      jarfile: liiteri
      jarfolder: target
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}

  deploy-background:
    needs: [ test, build ]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@2f06269d5ac067ef17a76d2d5742db0b325e9a2e # main
    with:
      application: liiteri-background
      base-image: baseimage-fatjar-openjdk21:master
      configfolder: oph-configuration
      jarfile: liiteri
      jarfolder: target
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
